{
 "title": "Main dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Order Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "order_counter_total{job=\"Orchestrator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkout traces",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "99d4cd9a", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "Orchestrator" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "status",
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "valueType": "keyword"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Orders accepted/rejected",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "accepted_order_counter_total{job=\"Orchestrator\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "rejected_order_counter_total{job=\"Orchestrator\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Database book counter",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "book_counter_ratio{job=\"Books database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order execution traces",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 9 },
   "targets": [
    {
     "filters": [
      { "id": "1dfbb0b8", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "Order executor" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=~",
       "scope": "span",
       "tag": "name",
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Order queue size",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "queue_size{job=\"Order queue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average order time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_order_time_ratio{job=\"Orchestrator\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total payments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "payment_total{job=\"Payment service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkout activity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(aaa_bucket{job=\"Orchestrator\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}