# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books_database.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62ooks_database.proto\x12\x0e\x62ooks_database\"0\n\rStockResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x03\" \n\x0fGetStockRequest\x12\r\n\x05title\x18\x01 \x01(\t\"2\n\x0fSetStockRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x03\x32\x88\x02\n\x14\x42ooksDatabaseService\x12L\n\x08GetStock\x12\x1f.books_database.GetStockRequest\x1a\x1d.books_database.StockResponse\"\x00\x12L\n\x08SetStock\x12\x1f.books_database.SetStockRequest\x1a\x1d.books_database.StockResponse\"\x00\x12T\n\x10ReplicateChanges\x12\x1f.books_database.SetStockRequest\x1a\x1d.books_database.StockResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_database_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STOCKRESPONSE']._serialized_start=40
  _globals['_STOCKRESPONSE']._serialized_end=88
  _globals['_GETSTOCKREQUEST']._serialized_start=90
  _globals['_GETSTOCKREQUEST']._serialized_end=122
  _globals['_SETSTOCKREQUEST']._serialized_start=124
  _globals['_SETSTOCKREQUEST']._serialized_end=174
  _globals['_BOOKSDATABASESERVICE']._serialized_start=177
  _globals['_BOOKSDATABASESERVICE']._serialized_end=441
# @@protoc_insertion_point(module_scope)
