# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import books_database_pb2 as books__database__pb2


class BooksDatabaseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStock = channel.unary_unary(
                '/books_database.BooksDatabaseService/GetStock',
                request_serializer=books__database__pb2.GetStockRequest.SerializeToString,
                response_deserializer=books__database__pb2.StockResponse.FromString,
                )
        self.SetStock = channel.unary_unary(
                '/books_database.BooksDatabaseService/SetStock',
                request_serializer=books__database__pb2.SetStockRequest.SerializeToString,
                response_deserializer=books__database__pb2.StockResponse.FromString,
                )
        self.ReplicateChanges = channel.unary_unary(
                '/books_database.BooksDatabaseService/ReplicateChanges',
                request_serializer=books__database__pb2.SetStockRequest.SerializeToString,
                response_deserializer=books__database__pb2.StockResponse.FromString,
                )


class BooksDatabaseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateChanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BooksDatabaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStock,
                    request_deserializer=books__database__pb2.GetStockRequest.FromString,
                    response_serializer=books__database__pb2.StockResponse.SerializeToString,
            ),
            'SetStock': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStock,
                    request_deserializer=books__database__pb2.SetStockRequest.FromString,
                    response_serializer=books__database__pb2.StockResponse.SerializeToString,
            ),
            'ReplicateChanges': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateChanges,
                    request_deserializer=books__database__pb2.SetStockRequest.FromString,
                    response_serializer=books__database__pb2.StockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'books_database.BooksDatabaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BooksDatabaseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books_database.BooksDatabaseService/GetStock',
            books__database__pb2.GetStockRequest.SerializeToString,
            books__database__pb2.StockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books_database.BooksDatabaseService/SetStock',
            books__database__pb2.SetStockRequest.SerializeToString,
            books__database__pb2.StockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplicateChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books_database.BooksDatabaseService/ReplicateChanges',
            books__database__pb2.SetStockRequest.SerializeToString,
            books__database__pb2.StockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
