# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_verification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x18transaction_verification\"\x89\x01\n\x13VerificationRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x14\n\x0cuser_contact\x18\x02 \x01(\t\x12\x15\n\rcreditcard_nr\x18\x03 \x01(\t\x12\r\n\x05items\x18\x04 \x03(\t\x12\x12\n\nquantities\x18\x05 \x03(\x05\x12\x0f\n\x07orderId\x18\x06 \x01(\t\"$\n\x14VerificationResponse\x12\x0c\n\x04isOk\x18\x01 \x01(\x08\"P\n\x12VectorClockRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x13\n\x0bvectorClock\x18\x02 \x03(\x05\x12\x14\n\x0cshouldCancel\x18\x03 \x01(\x08\"\x07\n\x05\x45mpty2\xf3\x01\n\x13VerificationService\x12x\n\x17TransactionVerification\x12-.transaction_verification.VerificationRequest\x1a..transaction_verification.VerificationResponse\x12\x62\n\x11UpdateVectorClock\x12,.transaction_verification.VectorClockRequest\x1a\x1f.transaction_verification.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VERIFICATIONREQUEST']._serialized_start=61
  _globals['_VERIFICATIONREQUEST']._serialized_end=198
  _globals['_VERIFICATIONRESPONSE']._serialized_start=200
  _globals['_VERIFICATIONRESPONSE']._serialized_end=236
  _globals['_VECTORCLOCKREQUEST']._serialized_start=238
  _globals['_VECTORCLOCKREQUEST']._serialized_end=318
  _globals['_EMPTY']._serialized_start=320
  _globals['_EMPTY']._serialized_end=327
  _globals['_VERIFICATIONSERVICE']._serialized_start=330
  _globals['_VERIFICATIONSERVICE']._serialized_end=573
# @@protoc_insertion_point(module_scope)
