# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_verification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x05hello\"x\n\x13VerificationRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x14\n\x0cuser_contact\x18\x02 \x01(\t\x12\x15\n\rcreditcard_nr\x18\x03 \x01(\t\x12\r\n\x05items\x18\x04 \x03(\t\x12\x12\n\nquantities\x18\x05 \x03(\x05\"$\n\x14VerificationResponse\x12\x0c\n\x04isOk\x18\x01 \x01(\x08\x32i\n\x13VerificationService\x12R\n\x17TransactionVerification\x12\x1a.hello.VerificationRequest\x1a\x1b.hello.VerificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VERIFICATIONREQUEST']._serialized_start=41
  _globals['_VERIFICATIONREQUEST']._serialized_end=161
  _globals['_VERIFICATIONRESPONSE']._serialized_start=163
  _globals['_VERIFICATIONRESPONSE']._serialized_end=199
  _globals['_VERIFICATIONSERVICE']._serialized_start=201
  _globals['_VERIFICATIONSERVICE']._serialized_end=306
# @@protoc_insertion_point(module_scope)
